services:
  home-iot-server:
    build: .
    container_name: iot-server
    ports:
      - "3001:3001"
    # .env 파일의 모든 변수를 컨테이너 내부로 자동 주입
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      default:
        aliases:
          - iot-app

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: iot-postgres
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heechan -d home_iot"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=postgres"]

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: iot-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: iot-tunnel
    restart: always
    command: tunnel --no-autoupdate run --credentials-file /home/nonroot/.cloudflared/5ea22a6e-e622-4d86-8618-29cd770abbda.json --url http://iot-server:3001 home-iot
    volumes:
      - /Users/heechan/.cloudflared:/home/nonroot/.cloudflared
    depends_on:
      - home-iot-server
